### ISSUE TITLE
STL10 setting in alpha-CL

### ISSUE THREAD

**Issue by junkangwu** [facebookresearch/luckmatters#11]
Hi, nice work!
When I re-implement alpha-CL performance on stl10, it doesn't work. Is it correct to set lr=1e-3, p=4, batch_size=256, and \tau=0.5 for ResNet50 (c.f. Table 3)?

**Comment by yuandong-tian** [comment]
Here is the raw performance log:
```
Conditional variables:
method: ['simclr']
network.name: ['resnet50']
trainer.batch_size: ['256']
trainer.nce_loss.loss_type: ['dual']
trainer.nce_loss.alpha_exponent: ['2']
trainer.nce_loss.alpha_eps: ['0']
trainer.nce_loss.alpha_type: ['exp']
use_optimizer: ['adam']
optimizer.params.lr: ['0.001']
optimizer.params.weight_decay: ['0']
trainer.max_epochs: ['500']
+githash: ['504b56d']

Sweep variables:
dataset: ['cifar10', 'cifar100', 'stl10']
seed: ['1', '2', '3', '4', '5']

Recent modified since:  2 days 12:22:18.488341
              acc_iter100      acc_iter300      acc_iter500   acc_iter100_len   acc_iter300_len   acc_iter500_len    folder
                      agg              agg              agg               agg               agg               agg       agg
dataset
cifar10   $87.91\pm 0.12$  $89.89\pm 0.18$  $91.06\pm 0.17$  $100.00\pm 0.00$  $300.00\pm 0.00$  $500.00\pm 0.00$  15-19[5]
cifar100  $63.47\pm 0.06$  $65.86\pm 0.24$  $66.57\pm 0.21$  $100.00\pm 0.00$  $300.00\pm 0.00$  $500.00\pm 0.00$  55-59[5]
stl10     $83.20\pm 0.17$  $87.36\pm 0.12$  $87.71\pm 0.14$  $100.00\pm 0.00$  $300.00\pm 0.00$  $500.00\pm 0.00$  35-39[5]
```

Here is the complete command line 
```
python main.py method=simclr network.name=resnet50 dataset=stl10 trainer.batch_size=256 trainer.nce_loss.loss_type=dual trainer.nce_loss.alpha_exponent=2 trainer.nce_loss.alpha_eps=0 trainer.nce_loss.alpha_type=exp use_optimizer=adam optimizer.params.lr=0.001 optimizer.params.weight_decay=0 seed=1 trainer.max_epochs=500 +githash=504b56d
```

and hydra switches:
```
network:
  name: resnet50
  pretrained_path: None
  conv_spec:
    variant: regular
    freq: 100
    resample_ratio: 0.05
    layer_involved: conv1-conv2
    include_first_conv: false
  bn_spec:
    enable_bn1: true
    enable_bn2: true
    bn_variant: regular
  projection_head:
    mlp_hidden_size: 512
    projection_size: 128
  predictor_head:
    mlp_hidden_size: 512
    projection_size: 128
aug:
  jitter: 1
  prob_hflip: 0.5
  prob_grayscale: 0.2
  blur_sz: 0.1
method: simclr
trainer:
  batch_size: 256
  save_per_epoch: 20
  m: 0.996
  checkpoint_interval: 5000
  max_epochs: 500
  num_workers: 16
  target_noise: 0.005
  train_predictor: true
  has_predictor: true
  projector_params:
    has_bias: true
    has_relu: true
    custom_nz: null
    normalization: bn
    has_bn_affine: false
    additional_bn_at_input: false
    custom_bn:
      mean: normal
      std: normal
  predictor_params:
    has_bias: true
    has_relu: true
    custom_nz: null
    normalization: bn
    has_bn_affine: false
    additional_bn_at_input: false
    custom_bn:
      mean: normal
      std: normal
  projector_same_as_predictor: false
  predictor_init:
    low: null
    high: null
  nce_loss:
    temperature: 0.5
    use_cosine_similarity: true
    beta: 0
    add_one_in_neg: false
    loss_type: dual
    exact_cov_unaug_sim: false
    alpha_type: exp
    alpha_exponent: 2
    alpha_eps: 0
    inverse_exponent: 1
    low_rank: null
  l2_reg_type: regular
  grad_combination_margin: null
  predictor_reg: symmetric
  predictor_freq: 0
  predictor_rank: 0.5
  predictor_eig: 0.5
  predictor_eps: 1.0e-05
  dyn_time: null
  dyn_eps: 0.0
  dyn_eps_inside: false
  dyn_reg: null
  dyn_zero_mean: false
  dyn_lambda: 0.8
  dyn_psd: null
  dyn_bn: false
  dyn_diagonalize: false
  dyn_sym: true
  dyn_convert: 2
  dyn_noise: null
  corr_collect: false
  use_l2_normalization: true
  predictor_wd: null
  balance_type: clamp
  n_corr: 2
  solve_direction: left
  init_rand_pred: false
  rand_pred_n_epoch: 0
  rand_pred_n_iter: 0
  rand_pred_reg: all
  noise_blend: 0.0
  use_order_of_variance: false
  corr_eigen_decomp: true
use_optimizer: adam
predictor_optimizer_same: true
optimizer:
  params:
    lr: 0.001
    momentum: 0.9
    weight_decay: 0
predictor_optimizer:
  params:
    lr: 0.03
    momentum: 0.9
    weight_decay: 0.0004
dataset_path: /checkpoint/yuandong/datasets
dataset: stl10
seed: 1
gpu: 0
eval_after_each_epoch: true
githash: 504b56d
test:
  exp_name_list: ''
  load_epoch_list: []
  batch_size: 512
```
